# Generated by Django 6.1.1 on 2026-09-11 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('slug', models.SlugField(max_length=200, verbose_name='اسلاگ')),
                ('status', models.CharField(choices=[('DF', 'DRAFT'), ('RJ', 'REJECTED'), ('ACC', 'ACCEPTED')], default='DF', max_length=3, verbose_name='وضعیت انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['title', 'published_at'], name='blog_post_title_cf4a49_idx')],
            },
        ),
    ]
