# Generated by Django 6.1.1 on 2026-10-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'DRAFT'), ('RJ', 'REJECTED'), ('ACC', 'ACCEPTED')], default='DF', max_length=3, verbose_name='وضعیت انتشار'),
        ),
    ]
