# Generated by Django 6.1.1 on 2026-10-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=70, verbose_name=' نام خانوادگی')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=False, verbose_name='نمایش / عدم نمایش')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه ها',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['first_name', 'created_at'], name='blog_commen_first_n_69a9b6_idx')],
            },
        ),
    ]
