# Generated by Django 6.1.1 on 2026-09-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['created_at'], 'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='response',
            field=models.TextField(default='URP', verbose_name='پاسخ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('RP', 'RESPONDED'), ('URP', 'UNRESPONDED')], default='URP', max_length=3, verbose_name='وضعیت پاسخ دهی'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['subject', 'created_at'], name='ticket_tick_subject_3361cc_idx'),
        ),
    ]
