# Generated by Django 6.1.1 on 2026-09-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_options_ticket_response_ticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('RP', 'RESPONDED'), ('URP', 'UNRESPONDED')], default='URP', editable=False, max_length=3, verbose_name='وضعیت پاسخ دهی'),
        ),
    ]
