# Generated by Django 6.1.1 on 2026-09-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ'),
        ),
    ]
