# Generated by Django 6.1.1 on 2026-09-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('RP', 'RESPONDED'), ('URP', 'UNRESPONDED')], default='URP', max_length=3, verbose_name='وضعیت پاسخ دهی'),
        ),
    ]
