# Generated by Django 6.1.1 on 2026-10-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('RP', 'RESPONDED'), ('URP', 'UNRESPONDED')], default='URP', max_length=3, verbose_name='وضعیت'),
        ),
    ]
